### ISSUE TITLE
Could the depth estimation be improved with this?

### ISSUE THREAD

**Issue by vdruts** [luciddreamer-cvlab/LucidDreamer#10]
https://github.com/prs-eth/marigold

**Comment by esw0116** [comment]
Hello, thank you for the comment.
We actually adopt Marigold for depth estimation instead of Zoedepth, but naively replacing it produces worse results with sharp artifacts.
We should add some additional post-processing after depth estimation to enhance the quality.
We expect better results than current output using Marigold since it provides more accurate depth information.
We will soon add Marigold as a new depth estimation option.
