### ISSUE TITLE
Is there option to input multiple images to reconstruct the scene?

### ISSUE THREAD

**Issue by song6174** [luciddreamer-cvlab/LucidDreamer#13]
As I tested the back of the scene does not have much details, I hope adding more images would help solve that problem as the original gaussian splatting does. I do like your build for the gaussian splatting.

**Comment by esw0116** [comment]
Hello,
we acknowledge that the details of the scene become are less represented because the number of images for the optimization is not sufficient.
Yet, the reprojected images are sometimes severely deteriorated, which are mostly caused by the accumulation of errors at depth estimation.
It frequently occurs when generating objects with complex structures e.g. trees with leaves or animals with furs.
This guides the Gaussian splats to locate in wrong position, decreasing the quality of the overall 3D scene representation.
We are trying to alleviate the issue and enhance the quality by incorporating with more accurate depth estimation model ([Marigold](https://marigoldmonodepth.github.io/)).

**Comment by song6174** [comment]
Thanks for the updates!
