### ISSUE TITLE
prompt

### ISSUE THREAD

**Issue by Tiandishihua** [luciddreamer-cvlab/LucidDreamer#16]
What kind of text prompts and negative prompts should I input to generate the expected results when I input a scene photo I took.

**Comment by ironjr** [comment]
Thanks for your attention! I would like to recommend trying example codes in the main `app.py` first, since we have demonstrated different types of text prompts there.

With my experience, as a rule of thumb, you may try this procedure.

1. If your image is indoors with specific scene (and possible character in it), you can just put the most simplest representation of the scene first, like `a cozy livingroom for christmas`, or `a dark garage`, etc. Please avoid prompts like `1girl` because it will generate many humans for each inpainting task.
2. If you want to start from already hard-engineered image from e.g., StableDiffusion model, or a photo taken from other sources, you can try using [WD14 tagger](https://huggingface.co/spaces/deepghs/wd14_tagging_online) to extract the danbooru tags from an image. Please ensure you remove some comma separated tags if you don't want them to appear multiple times. This include human-related objects, e.g., `1girl`, `white shirt`, `boots`, `smiling face`, `red eyes`, etc. Make sure to specify the objects you want to have multiples of them.

These are the main strategy I have demonstrated in my twitter account and the huggingface demo. I hope you find this guide useful. I will also update our README file regarding your question.
