### ISSUE TITLE
Error when installing "depth-diff-gaussian-rasterization-min" (CUDA version mismatch)

### ISSUE THREAD

**Issue by Chrisz236** [luciddreamer-cvlab/LucidDreamer#25]
Hi team, I follow the instructions to install and run under the Ubuntu environment. However, I am encountering an error when running `python setup.py install` in the path `submodules/depth-diff-gaussian-rasterization-min`. The error message suggests the CUDA version is mismatched:
`RuntimeError:
The detected CUDA version (12.2) mismatches the version that was used to compile
PyTorch (11.7). Please make sure to use the same CUDA versions.`

I have pytorch 2.0.1 installed. is there any solution to fix this without downgrading the system CUDA? Thanks.

**Comment by esw0116** [comment]
Hello, I think the version of CUDA and Pytorch Cudatoolkit should be matched to install the submodules.
To the best of our knowledge, there is no Pytorch version compatible for CUDA 12.2 yet.
Since multiple versions of CUDA can be installed in a same machine, I recommend you to install CUDA 11.7 or 11.8 and change the PATH of CUDA in .bashrc file.
If you cannot install another version of CUDA, I am afraid that the submodules cannot be successfully installed.

**Comment by Chrisz236** [comment]
Alright, I’ll try to downgrade the CUDA then try to install again. Thanks

**Comment by esw0116** [comment]
Thanks, please re-open the issue when you face any problems.
